# Element size ratio list
weights_list: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

primitive_pos_init_type: "distance_field" # "distance_field","random_within_shape","medial_axis"
is_global_size: False # Strictly follow the weight list
is_rotate: True
is_rotate_random: False
primitive_fill_ratio: 0.55 # Initial element size percentage
num_iters: 100

svg_normalized_size: 100
raster_normalized_size: 500
outline_num_segments: 40

base_lr:
  size: 0.002
  angle: 0.05
  pos: 0.2

